python3 predict.py --models trained/final_111_DeepFakeClassifier_tf_efficientnet_b7_ns_0_36

python3 predict.py --models trained/final_555_DeepFakeClassifier_tf_efficientnet_b7_ns_0_19

python3 predict.py --models trained/final_777_DeepFakeClassifier_tf_efficientnet_b7_ns_0_29

python3 predict.py --models trained/final_777_DeepFakeClassifier_tf_efficientnet_b7_ns_0_31

python3 predict.py --models trained/final_888_DeepFakeClassifier_tf_efficientnet_b7_ns_0_37

python3 predict.py --models trained/final_888_DeepFakeClassifier_tf_efficientnet_b7_ns_0_40

python3 predict.py --models trained/final_999_DeepFakeClassifier_tf_efficientnet_b7_ns_0_23
